### GET /api/v1
GET http://localhost:8080/api/v1

###

### GET /api/v1/users
GET http://localhost:8080/api/v1/users

###

### GET /api/v1/users/:user_id
GET http://localhost:8080/api/v1/users/1

###

### POST /api/v1/users
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "joh@email.com",
  "password": "password"
}

###

### PUT /api/v1/users/:user_id
PUT http://localhost:8080/api/v1/users/1
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@email.com"
}

###

### DELETE /api/v1/users/:user_id
DELETE http://localhost:8080/api/v1/users/1

###

### GET /api/unknown
GET http://localhost:8080/api/unknown

###

### POST /api/v1
POST http://localhost:8080/api/v1
